language: elixir

# Elixir + OTP compatibility: https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
elixir:
  - 1.4 # supports OTP 18-19 (and 20 with 1.4.5+)
  - 1.5 # supports OTP 18-20
  - 1.6 # supports OTP 19-20 (and 21 with v1.6.6+)
  - 1.7 # supports OTP 19-22
  - 1.8 # supports OTP 20-22
  - 1.9 # supports OTP 20-22

otp_release:
  - 18.3
  - 19.3
  - 20.3
  - 21.3
  - 22.0

matrix:
  exclude:
    - elixir: 1.4
      otp_release: 20.3
    - elixir: 1.4
      otp_release: 21.3
    - elixir: 1.4
      otp_release: 22.0
    - elixir: 1.5
      otp_release: 21.3
    - elixir: 1.5
      otp_release: 22.0
    - elixir: 1.6
      otp_release: 21.3
    - elixir: 1.6
      otp_release: 22.0
    - elixir: 1.8
      otp_release: 19.3
    - elixir: 1.9
      otp_release: 19.3
