language: elixir
elixir:
- 1.4
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
otp_release:
- 18.3
- 19.3
- 20.3
- 21.3
- 22.0
matrix:
  exclude:
  - elixir: 1.4
    otp_release: 20.3
  - elixir: 1.4
    otp_release: 21.3
  - elixir: 1.4
    otp_release: 22.0
  - elixir: 1.5
    otp_release: 21.3
  - elixir: 1.5
    otp_release: 22.0
  - elixir: 1.6
    otp_release: 21.3
  - elixir: 1.6
    otp_release: 22.0
  - elixir: 1.8
    otp_release: 19.3
  - elixir: 1.9
    otp_release: 19.3
before_install:
- openssl aes-256-cbc -K $encrypted_1fc90f464345_key -iv $encrypted_1fc90f464345_iv
  -in config/waffle-gcs-test.json.enc -out config/waffle-gcs-test.json -d
- export GCP_CREDENTIALS=`cat config/waffle-gcs-test.json`
